services:
  php-apache:
    container_name: job_listener
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    networks:
      - job-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: job_listener_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_listener
      MYSQL_USER: job_listener
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - job-network

networks:
  job-network:
    driver: bridge

volumes:
  mysql_data: